num1 = int(input("Enter an integer:"))
num2 = int(input("Enter an integer:"))
print(num1, "+", num2, "=", num1 + num2)
print(num1, "-", num2, "=", num1 - num2)
print(num1, "*", num2, "=", num1 * num2)
